javac socket/*.java
javac Graph/*.java
javac Listener/*.java
javac socket_c/*.java
javac Graph_c/*.java
javac Listener_c/*.java
javac graph_menu/*.java
javac thread/*.java
javac menu_listener/*.java
javac main/*.java
java main/Pong_main
